import javax.swing.*;
import java.io.*;

public class HistoryForm extends javax.swing.JFrame {

    // Stores the currently logged-in username
    private String username;

    // Logger (auto-generated, optional)
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(HistoryForm.class.getName());

    /**
     * Constructor
     * @param user - the username passed from login/dashboard
     */
    public HistoryForm(String user) {
        username = user;          // save username
        initComponents();         // build the GUI
        setLocationRelativeTo(null); // center the window
        loadHistory();            // load transactions for this user
    }

    /**
     * Initializes all Swing components
     * ⚠ Auto-generated by NetBeans GUI Builder
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHistory = new javax.swing.JTextArea();
        btnResetHistory = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Title label
        lblTitle.setText("TRANSACTION HISTORY");

        // Close button
        btnClose.setText("Cancel");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        // Text area where history is shown
        txtHistory.setEditable(false); // read-only
        txtHistory.setColumns(50);
        txtHistory.setRows(15);
        jScrollPane3.setViewportView(txtHistory);

        // Reset history button
        btnResetHistory.setText("Reset");
        btnResetHistory.addActionListener(this::btnResetHistoryActionPerformed);

        // Layout settings (GUI positioning)
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addComponent(btnResetHistory)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnClose)))
                .addContainerGap(49, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262,
                        javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnClose)
                    .addComponent(btnResetHistory))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    /**
     * Close button action
     */
    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {
        dispose(); // close the window
    }

    /**
     * Reset (delete) ALL transaction history
     */
    private void btnResetHistoryActionPerformed(java.awt.event.ActionEvent evt) {

        // Confirmation dialog
        int confirm = JOptionPane.showConfirmDialog(
            this,
            "Are you sure you want to delete ALL transaction history?",
            "Confirm Reset",
            JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return; // cancel reset
        }

        try {
            // Overwrite file with empty content
            new FileWriter("transactions.txt", false).close();

            JOptionPane.showMessageDialog(
                this,
                "Transaction history has been reset successfully."
            );

            // Update UI
            txtHistory.setText("Transaction history has been cleared.");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(
                this,
                "Error resetting transaction history."
            );
            e.printStackTrace();
        }
    }

    /**
     * Loads transaction history for the current user
     */
    private void loadHistory() {

        File file = new File("transactions.txt");

        // If file does not exist
        if (!file.exists()) {
            txtHistory.setText("No transactions found.");
            return;
        }

        try (BufferedReader br = new BufferedReader(new FileReader(file))) {

            String line;
            boolean hasData = false;
            txtHistory.setText("");

            while ((line = br.readLine()) != null) {

                // Split line: username,date,type,amount,details
                String[] d = line.split(",", -1);

                if (d.length < 5) continue; // skip invalid lines

                // Show only transactions of the logged-in user
                if (d[0].equals(username)) {
                    hasData = true;

                    double amt;
                    try {
                        amt = Double.parseDouble(d[3]);
                    } catch (NumberFormatException nfe) {
                        amt = 0;
                    }

                    String amountFormatted = String.format("₱%.2f", amt);

                    // One-line transaction format
                    String oneLine = String.format(
                        "%s | %s | %s | %s\n",
                        d[1],            // date
                        d[2],            // type
                        amountFormatted,// amount
                        d[4]             // details
                    );

                    txtHistory.append(oneLine);
                }
            }

            if (!hasData) {
                txtHistory.setText("No transactions yet.");
            }

        } catch (Exception e) {
            txtHistory.setText("Error loading history.");
            e.printStackTrace();
        }
    }

    /**
     * Test main method
     */
    public static void main(String[] args) {
        SwingUtilities.invokeLater(
            () -> new HistoryForm("YourUsernameHere").setVisible(true)
        );
    }

    // Variables declaration - do not modify
    private javax.swing.JButton btnClose;
    private javax.swing.JButton btnResetHistory;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtHistory;
    // End of variables declaration
}
