import javax.swing.*;
import java.io.*;

public class TransferForm extends javax.swing.JFrame {

    // Logger for debugging and error tracking
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(TransferForm.class.getName());

    // Stores the logged-in sender username
    String username;

    // Constructor receives sender username from Dashboard
    public TransferForm(String user) {
        initComponents();          // initialize GUI
        username = user;           // assign logged-in user
        setLocationRelativeTo(null); // center the form
    }

    @SuppressWarnings("unchecked")
    private void initComponents() {

        // GUI components
        lblTitle = new javax.swing.JLabel();
        lblRecipient = new javax.swing.JLabel();
        txtRecipient = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnTransfer = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Form title
        lblTitle.setText("TRANSFER");

        // Recipient label
        lblRecipient.setText("Recipient Username");

        // Amount label
        jLabel1.setText("Amount");

        // Transfer button
        btnTransfer.setText("Transfer");
        btnTransfer.addActionListener(this::btnTransferActionPerformed);

        // Cancel button
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        // Layout (auto-generated by NetBeans)
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(199, 199, 199)
                        .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnCancel)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(82, 82, 82)
                                    .addComponent(lblRecipient))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(98, 98, 98)
                                    .addComponent(jLabel1))))
                        .addGap(67, 67, 67)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING,
                                     layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(txtRecipient, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(btnTransfer, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap(137, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRecipient)
                    .addComponent(txtRecipient, javax.swing.GroupLayout.PREFERRED_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(42, 42, 42)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTransfer)
                    .addComponent(btnCancel))
                .addContainerGap(100, Short.MAX_VALUE))
        );

        pack(); // adjust window size
    }

    // Handles Transfer button click
    private void btnTransferActionPerformed(java.awt.event.ActionEvent evt) {

        // Get recipient username
        String recipient = txtRecipient.getText().trim();
        double amount;

        // Validate amount input
        try {
            amount = Double.parseDouble(txtAmount.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Enter a valid amount!");
            return;
        }

        // Validate recipient input
        if (recipient.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Enter recipient username!");
            return;
        }

        // Prevent self-transfer
        if (recipient.equals(username)) {
            JOptionPane.showMessageDialog(this, "Cannot transfer to yourself!");
            return;
        }

        // Perform transfer
        boolean success = transferMoney(username, recipient, amount);

        if (success) {
            // Save sender and recipient transaction records
            saveTransaction(username, "Transfer Sent", amount, "To " + recipient);
            saveTransaction(recipient, "Transfer Received", amount, "From " + username);

            JOptionPane.showMessageDialog(this, "Transfer successful!");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this,
                    "Insufficient balance or recipient not found!");
        }
    }

    // Transfers money between two users
    private boolean transferMoney(String sender, String recipient, double amt) {

        File input = new File("users.txt");
        File temp = new File("temp.txt");

        boolean senderFound = false, recipientFound = false;
        double senderBalance = 0;

        // FIRST PASS: validate sender and recipient
        try (BufferedReader br = new BufferedReader(new FileReader(input))) {
            String line;
            while ((line = br.readLine()) != null) {
                String[] d = line.split(",");
                if (d[0].equals(sender)) {
                    senderBalance = Double.parseDouble(d[3]);
                    senderFound = true;
                }
                if (d[0].equals(recipient)) {
                    recipientFound = true;
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }

        // Validation check
        if (!senderFound || !recipientFound || senderBalance < amt) {
            return false;
        }

        // SECOND PASS: update balances
        try (BufferedReader br = new BufferedReader(new FileReader(input));
             PrintWriter pw = new PrintWriter(new FileWriter(temp))) {

            String line;
            while ((line = br.readLine()) != null) {
                String[] d = line.split(",");

                if (d[0].equals(sender)) {
                    double newBal = Double.parseDouble(d[3]) - amt;
                    pw.println(d[0] + "," + d[1] + "," + d[2] + "," + newBal);
                } else if (d[0].equals(recipient)) {
                    double newBal = Double.parseDouble(d[3]) + amt;
                    pw.println(d[0] + "," + d[1] + "," + d[2] + "," + newBal);
                } else {
                    pw.println(line);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
            return false;
        }

        // Replace old file
        input.delete();
        temp.renameTo(input);

        return true;
    }

    // Cancel button closes the form
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    // Saves transfer transaction to transactions.txt
    private void saveTransaction(String user, String type, double amt, String details) {
        try (FileWriter fw = new FileWriter("transactions.txt", true)) {

            String date = java.time.LocalDateTime.now()
                    .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

            fw.write(user + "," + date + "," + type + "," +
                     String.format("%.2f", amt) + "," + details + "\n");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnTransfer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblRecipient;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAmount;
    private javax.swing.JTextField txtRecipient;
}
