import javax.swing.*;
import java.io.*;

public class HistoryForm extends javax.swing.JFrame {
    
    private String username;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(HistoryForm.class.getName());

    /**
     * Creates new form HistoryForm
     */
    public HistoryForm(String user) {
       username = user;
        initComponents();
        setLocationRelativeTo(null);
        loadHistory();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        btnClose = new javax.swing.JButton();
        jScrollPane3 = new javax.swing.JScrollPane();
        txtHistory = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("TRANSACTION HISTORY");

        btnClose.setText("Cancel");
        btnClose.addActionListener(this::btnCloseActionPerformed);

        txtHistory.setEditable(false);
        txtHistory.setColumns(50);
        txtHistory.setRows(15);
        jScrollPane3.setViewportView(txtHistory);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnClose)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(165, 165, 165)
                            .addComponent(lblTitle))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(47, 47, 47)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 408, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addComponent(lblTitle)
                .addGap(18, 18, 18)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 262, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnClose)
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnCloseActionPerformed(java.awt.event.ActionEvent evt) {                                         
        dispose();
    }                                        

   
      private void loadHistory() {
         File file = new File("transactions.txt");

    if (!file.exists()) {
        txtHistory.setText("No transactions found.");
        return;
    }

    try (BufferedReader br = new BufferedReader(new FileReader(file))) {
        String line;
        boolean hasData = false;
        txtHistory.setText("");

        while ((line = br.readLine()) != null) {
            String[] d = line.split(",", -1); // keep empty strings
            if (d.length < 5) continue;      // skip invalid lines

            if (d[0].equals(username)) {
                hasData = true;

                double amt = 0;
                try {
                    amt = Double.parseDouble(d[3]);
                } catch (NumberFormatException nfe) {
                    amt = 0;
                }
                String amountFormatted = String.format("₱%.2f", amt);

                // One-line transaction
                String oneLine = String.format(
                    "%s | %s | %s | %s\n",
                    d[1],           // date
                    d[2],           // type
                    amountFormatted, // amount
                    d[4]            // details
                );

                txtHistory.append(oneLine);
            }
        }

        if (!hasData) {
            txtHistory.setText("No transactions yet.");
        }

    } catch (Exception e) {
        txtHistory.setText("Error loading history.");
        e.printStackTrace();
    }
    }
        public static void main(String[] args) {
        SwingUtilities.invokeLater(() -> new HistoryForm("YourUsernameHere").setVisible(true));
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnClose;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextArea txtHistory;
    // End of variables declaration                   
}
