import javax.swing.*;
import java.io.*;

public class WithdrawForm extends javax.swing.JFrame  {
    String username;
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(WithdrawForm.class.getName());


    public WithdrawForm(String username) {
        this.username = username;
        initComponents();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnWithdraw = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jLabel1.setText("jLabel1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblTitle.setText("Withdraw");

        lblAmount.setText("Amount");

        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(this::btnWithdrawActionPerformed);

        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(218, 218, 218)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(36, 36, 36)
                                .addComponent(btnWithdraw)))))
                .addContainerGap(175, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdraw)
                    .addComponent(btnCancel))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>                        

    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {                                            
        double amount = Double.parseDouble(txtAmount.getText());
        if (updateBalance(amount)) {
            saveTransaction("Withdraw", amount, "Cash withdrawal");
            JOptionPane.showMessageDialog(this, "Withdrawal successful");
            dispose();
        } else {
            JOptionPane.showMessageDialog(this, "Insufficient balance!");
        }
    }                                           

    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {                                          
        dispose();
    }                                         
 private boolean updateBalance(double amt) {
        File input = new File("users.txt");
        File temp = new File("temp.txt");
        boolean success = false;

        try (BufferedReader br = new BufferedReader(new FileReader(input));
             FileWriter fw = new FileWriter(temp)) {

            String line;
            while ((line = br.readLine()) != null) {
                String[] d = line.split(",");
                if (d[0].equals(username)) {
                    double currentBalance = Double.parseDouble(d[3]);
                    if (currentBalance >= amt) {
                        double newBal = currentBalance - amt;
                        fw.write(d[0] + "," + d[1] + "," + d[2] + "," + newBal + "," + (d.length > 4 ? d[4] : "") + "\n");
                        success = true;
                    } else {
                        // Write original line if insufficient funds
                        fw.write(line + "\n");
                    }
                } else fw.write(line + "\n");
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        input.delete();
        temp.renameTo(input);
        return success;
    }

    private void saveTransaction(String type, double amt, String details) {
        try (FileWriter fw = new FileWriter("transactions.txt", true)) {
            String date = java.time.LocalDateTime.now().toString();
            fw.write(username + "," + date + "," + type + "," + amt + "," + details + "\n");
        } catch (Exception e) {
            e.printStackTrace();
        }
    /**
     * @param args the command line arguments
     */
    
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
 
    }

    // Variables declaration - do not modify                     
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAmount;
    // End of variables declaration                   
}
