import javax.swing.*;
import java.io.*;

public class WithdrawForm extends javax.swing.JFrame {

    // Stores the currently logged-in username
    String username;

    // Logger for error handling
    private static final java.util.logging.Logger logger =
            java.util.logging.Logger.getLogger(WithdrawForm.class.getName());

    // Constructor receives username from Dashboard
    public WithdrawForm(String username) {
        this.username = username;      // assign logged-in user
        initComponents();              // initialize GUI components
        setLocationRelativeTo(null);   // center the form
    }

    /**
     * This method initializes the Swing components.
     * WARNING: Do NOT modify this code manually.
     */
    @SuppressWarnings("unchecked")
    private void initComponents() {

        // GUI components
        jLabel1 = new javax.swing.JLabel();
        lblTitle = new javax.swing.JLabel();
        lblAmount = new javax.swing.JLabel();
        txtAmount = new javax.swing.JTextField();
        btnWithdraw = new javax.swing.JButton();
        btnCancel = new javax.swing.JButton();

        jLabel1.setText("jLabel1"); // unused default label

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        // Form title
        lblTitle.setText("Withdraw");

        // Amount label
        lblAmount.setText("Amount");

        // Withdraw button
        btnWithdraw.setText("Withdraw");
        btnWithdraw.addActionListener(this::btnWithdrawActionPerformed);

        // Cancel button
        btnCancel.setText("Cancel");
        btnCancel.addActionListener(this::btnCancelActionPerformed);

        // Layout (auto-generated by NetBeans)
        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);

        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(210, 210, 210)
                            .addComponent(lblTitle, javax.swing.GroupLayout.PREFERRED_SIZE, 68, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGap(218, 218, 218)
                            .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblAmount, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnCancel)
                                .addGap(36, 36, 36)
                                .addComponent(btnWithdraw)))))
                .addContainerGap(175, Short.MAX_VALUE))
        );

        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(lblTitle)
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAmount, javax.swing.GroupLayout.PREFERRED_SIZE,
                                  javax.swing.GroupLayout.DEFAULT_SIZE,
                                  javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblAmount))
                .addGap(60, 60, 60)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnWithdraw)
                    .addComponent(btnCancel))
                .addContainerGap(157, Short.MAX_VALUE))
        );

        pack(); // adjust window size
    }

    // Withdraw button logic
    private void btnWithdrawActionPerformed(java.awt.event.ActionEvent evt) {

        // Convert entered amount to double
        double amount = Double.parseDouble(txtAmount.getText());

        // Attempt to update balance
        if (updateBalance(amount)) {

            // Save withdrawal transaction
            saveTransaction("Withdraw", amount, "Cash withdrawal");

            // Success message
            JOptionPane.showMessageDialog(this, "Withdrawal successful");

            // Close form
            dispose();
        } else {
            // Insufficient balance
            JOptionPane.showMessageDialog(this, "Insufficient balance!");
        }
    }

    // Cancel button closes the form
    private void btnCancelActionPerformed(java.awt.event.ActionEvent evt) {
        dispose();
    }

    // Updates user balance if sufficient funds exist
    private boolean updateBalance(double amt) {

        File input = new File("users.txt"); // original file
        File temp = new File("temp.txt");   // temporary file
        boolean success = false;

        try (BufferedReader br = new BufferedReader(new FileReader(input));
             FileWriter fw = new FileWriter(temp)) {

            String line;

            // Read all users
            while ((line = br.readLine()) != null) {
                String[] d = line.split(",");

                // If username matches
                if (d[0].equals(username)) {
                    double currentBalance = Double.parseDouble(d[3]);

                    // Check sufficient balance
                    if (currentBalance >= amt) {
                        double newBal = currentBalance - amt;

                        // Write updated balance
                        fw.write(d[0] + "," + d[1] + "," + d[2] + "," +
                                 newBal + "," + (d.length > 4 ? d[4] : "") + "\n");
                        success = true;
                    } else {
                        // Write original record if insufficient funds
                        fw.write(line + "\n");
                    }
                } else {
                    // Write other users unchanged
                    fw.write(line + "\n");
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }

        // Replace old file with updated file
        input.delete();
        temp.renameTo(input);

        return success; // return withdrawal status
    }

    // Saves withdrawal transaction to transactions.txt
    private void saveTransaction(String type, double amt, String details) {
        try (FileWriter fw = new FileWriter("transactions.txt", true)) {

            // Current date and time
            String date = java.time.LocalDateTime.now()
                    .format(java.time.format.DateTimeFormatter.ofPattern("yyyy-MM-dd HH:mm:ss"));

            // Write transaction record
            fw.write(username + "," + date + "," + type + "," +
                     String.format("%.2f", amt) + "," + details + "\n");

        } catch (Exception e) {
            e.printStackTrace();
        }
    }

    // Variables declaration
    private javax.swing.JButton btnCancel;
    private javax.swing.JButton btnWithdraw;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblAmount;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JTextField txtAmount;
}
